### ISSUE TITLE
Add in scripts

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/analysis#1]
@trinberg -- could we add in the script/jupyter notebook used to generate the graphs and counts for the Seeded sheets?

**Comment by trinberg** [comment]
Just added in "URL Nomination Analysis" folder.  Note that the nomination data file (anonymized), agency codes, and subprimer progress files are all in there as well.

**Comment by dcwalk** [comment]
Thanks! not sure why I never closed this, aii!
